* Было так тяжело вставать, сейчас почему-то часто так бывает.
* Проснулся в 8:50 по будильнику, сказал Ларке что пора вставать. Переставил будильник на 9:30. До 9:30 валялся пытаясь заснуть, очень хотелось лежать и ничего не делать. Переставил на 9:45. Точно так же лениво валялся. После, когда Ларка доготовила еду - я встал, потянулся.
* Все утро ленился готовиться к ревью
* Что сделано
** Пуш нотификации
*** Разобрался с устройством сервиса
*** Отключил лишние нотификации
*** Добавил mint
*** Порефакторил сервис нотификаций
** Спам
*** Удалось завершить одну задачу
*** Другую не удалось, но было проведено хорошее исследование системы, затрагивающее много ее частей
** Распознавание mint транзакций и уведомлений
** Реализовал фильтрацию истории транзакций
** Разобрался с сервисом zerion-api
*** Реализовал поддержку mint транзакций в пуш уведомлениях
** Разобрался с устройством NFT сервиса в целом, порефакторил моменты, написал много тестов
*** Самая impactful сейчас
** В процессе ресерча по задаче Multichain NFT
*** Будет самая impactful задача
** Дежурство
* Слабости: когда что-то непонятно по началу, процесс идет слишком медленно и лениво, это меня угнетает.
** Иногда хочется сделать что-то самому, и на это трачу больше времени чем нужно. Можно было бы спросить, но периодически это бывает сложней, чем кажется.
* Сила: когда стало понятно, что делать - процесс реализации и исследования идет очень хорошо, эффективно и доставляет уйму удовольствия и удовлетворения при получении результата
*
*